#!/usr/bin/env node
// Copies the pure, DOM-free app modules the CLI reuses into cli/vendor/, so the
// published npm package is self-contained (zero runtime deps) while the web app
// stays the single source of truth. Walks the static import/export graph from a
// seed set so the closure is always complete — if the app adds a new pure
// dependency, it's picked up automatically. The drift test asserts vendor files
// are byte-identical to source; the import smoke test asserts they load with no
// DOM. Run via `npm run sync-vendor` (also runs on prepublishOnly).
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const APP_DIR = join(here, '..', '..');          // mtgcollection/
const VENDOR_DIR = join(here, '..', 'vendor');

// Modules the CLI imports directly. Transitive pure deps are discovered by BFS.
const SEEDS = [
  'searchCore.js',
  'collection.js',
  'adapters.js',
  'importParsing.js',
  'importMerge.js',
  'syncOps.js',
  'portableArchive.js',
  'deckExport.js',
];

const IMPORT_RE = /(?:^|\n)\s*(?:import|export)\b[^;]*?\bfrom\s*['"](\.[^'"]+)['"]/g;

function relativeImports(source) {
  const out = [];
  let m;
  while ((m = IMPORT_RE.exec(source)) !== null) out.push(m[1]);
  return out;
}

function resolveLocal(spec) {
  // Only same-directory relative specifiers are expected (all app modules are
  // flat in mtgcollection/). Reject anything that escapes that assumption.
  const file = basename(spec);
  if (spec !== './' + file) {
    throw new Error(`Unexpected non-flat import "${spec}" — vendor closure assumes flat modules.`);
  }
  return file;
}

const seen = new Set();
const queue = [...SEEDS];
while (queue.length) {
  const file = queue.shift();
  if (seen.has(file)) continue;
  seen.add(file);
  const srcPath = join(APP_DIR, file);
  if (!existsSync(srcPath)) throw new Error(`Vendor source missing: ${file}`);
  const source = readFileSync(srcPath, 'utf8');
  for (const spec of relativeImports(source)) queue.push(resolveLocal(spec));
}

mkdirSync(VENDOR_DIR, { recursive: true });
// Remove stale vendored files no longer in the closure.
for (const existing of readdirSync(VENDOR_DIR)) {
  if (existing.endsWith('.js') && !seen.has(existing)) rmSync(join(VENDOR_DIR, existing));
}

const files = [...seen].sort();
for (const file of files) {
  writeFileSync(join(VENDOR_DIR, file), readFileSync(join(APP_DIR, file), 'utf8'));
}
writeFileSync(
  join(VENDOR_DIR, 'README.md'),
  '# vendor/\n\nGenerated by `scripts/sync-vendor.mjs` — do not edit by hand.\n\n'
  + 'These files are byte-identical copies of the biblioplex web app modules the\n'
  + 'CLI reuses (search grammar, CSV adapters, collection model, sync op diffing,\n'
  + 'deck export). The web app is the source of truth; re-run `npm run sync-vendor`\n'
  + 'after changing any of them.\n\nVendored modules:\n'
  + files.map(f => `- ${f}`).join('\n') + '\n'
);

console.log(`synced ${files.length} modules into vendor/:`);
console.log(files.map(f => '  ' + f).join('\n'));
