// Generated by scripts/sync-beliefs.mjs. Do not edit by hand.
window.BELIEFS = [
  {
    "id": "morality-001",
    "title": "Abortion should remain legal until birth",
    "status": "endorsed",
    "confidence": "medium",
    "lastReviewed": "2026-08-03",
    "tags": [
      "abortion",
      "bodily-autonomy",
      "medical-care",
      "law",
      "morality"
    ],
    "domain": "morality",
    "currentPoints": [
      "I have no moral objection to contraception or early abortion.",
      "A late elective abortion can be selfish, irresponsible, and seriously immoral without needing to be illegal.",
      "I would rather tolerate rare abuses than have the law block legitimate care it cannot reliably distinguish from them.",
      "A willing, qualified clinician should be allowed to provide an abortion until birth without the patient or clinician being criminally punished.",
      "Individual clinicians and hospitals should not ordinarily be compelled to provide an elective abortion. Emergency stabilization is a separate obligation.",
      "If ending a late pregnancy is necessary and live delivery would not materially increase the mother's risk, preserving the fetus feels morally preferable."
    ],
    "notYetSettled": [
      "Exactly how fetal moral status changes through development.",
      "What counts as a sufficiently serious health risk in difficult cases.",
      "Whether strongly unwanted parenthood reliably predicts worse outcomes for the parent or child."
    ],
    "sourcePath": "beliefs/morality/abortion-should-remain-legal-until-birth.md",
    "githubUrl": "https://github.com/benson/worldview/blob/main/beliefs/morality/abortion-should-remain-legal-until-birth.md",
    "searchText": "abortion should remain legal until birth morality abortion bodily-autonomy medical-care law morality i have no moral objection to contraception or early abortion. a late elective abortion can be selfish, irresponsible, and seriously immoral without needing to be illegal. i would rather tolerate rare abuses than have the law block legitimate care it cannot reliably distinguish from them. a willing, qualified clinician should be allowed to provide an abortion until birth without the patient or clinician being criminally punished. individual clinicians and hospitals should not ordinarily be compelled to provide an elective abortion. emergency stabilization is a separate obligation. if ending a late pregnancy is necessary and live delivery would not materially increase the mother's risk, preserving the fetus feels morally preferable."
  },
  {
    "id": "politics-001",
    "title": "Immigration rules should work in practice",
    "status": "endorsed",
    "confidence": "medium",
    "lastReviewed": "2026-08-02",
    "tags": [
      "immigration",
      "enforcement",
      "asylum",
      "employment-visas",
      "incentives"
    ],
    "domain": "politics",
    "currentPoints": [
      "I broadly support immigration, but not open borders or unfettered, unlimited immigration.",
      "I want immigration to be carefully monitored, gradual, and selective, including favoring high-skill immigrants and family connections.",
      "Immigration policy should be judged by how it actually works, not just by the rules written on paper.",
      "I think several current channels, including asylum and employment-based systems, are highly gameable or underenforced.",
      "Migrants, employers, and other participants sometimes knowingly exploit these systems.",
      "Long underenforcement creates painful dependencies, but that pain does not by itself make later enforcement unjust."
    ],
    "notYetSettled": [
      "The exact amount and selection criteria for legal immigration.",
      "The best reforms for asylum, employment visas, work authorization, and enforcement."
    ],
    "sourcePath": "beliefs/politics/immigration-rules-should-work-in-practice.md",
    "githubUrl": "https://github.com/benson/worldview/blob/main/beliefs/politics/immigration-rules-should-work-in-practice.md",
    "searchText": "immigration rules should work in practice politics immigration enforcement asylum employment-visas incentives i broadly support immigration, but not open borders or unfettered, unlimited immigration. i want immigration to be carefully monitored, gradual, and selective, including favoring high-skill immigrants and family connections. immigration policy should be judged by how it actually works, not just by the rules written on paper. i think several current channels, including asylum and employment-based systems, are highly gameable or underenforced. migrants, employers, and other participants sometimes knowingly exploit these systems. long underenforcement creates painful dependencies, but that pain does not by itself make later enforcement unjust."
  },
  {
    "id": "politics-002",
    "title": "Knowingly remaining illegally means accepting deportation risk",
    "status": "endorsed",
    "confidence": "medium",
    "lastReviewed": "2026-08-02",
    "tags": [
      "immigration",
      "deportation",
      "responsibility",
      "children",
      "enforcement"
    ],
    "domain": "politics",
    "currentPoints": [
      "If I knowingly enter or remain in another country illegally, I accept the risk of being deported.",
      "Building a job, family, or life on top of that choice does not by itself create a right to remain.",
      "Deportation can be tragic and painful without being unjust.",
      "If I was brought here without meaningfully choosing it, I incurred no moral debt for coming here.",
      "Responsibility tracks actual agency and understanding; turning eighteen is not a magical dividing line.",
      "A citizen child should be protected and given a safe transition, but their needs do not give the parent a right to stay. Separation can harm the child without making removal unjust; the parent chose to build the child's life around that risk."
    ],
    "notYetSettled": [
      "How to judge independent migration by older teenagers."
    ],
    "sourcePath": "beliefs/politics/knowingly-remaining-illegally-means-accepting-deportation-risk.md",
    "githubUrl": "https://github.com/benson/worldview/blob/main/beliefs/politics/knowingly-remaining-illegally-means-accepting-deportation-risk.md",
    "searchText": "knowingly remaining illegally means accepting deportation risk politics immigration deportation responsibility children enforcement if i knowingly enter or remain in another country illegally, i accept the risk of being deported. building a job, family, or life on top of that choice does not by itself create a right to remain. deportation can be tragic and painful without being unjust. if i was brought here without meaningfully choosing it, i incurred no moral debt for coming here. responsibility tracks actual agency and understanding; turning eighteen is not a magical dividing line. a citizen child should be protected and given a safe transition, but their needs do not give the parent a right to stay. separation can harm the child without making removal unjust; the parent chose to build the child's life around that risk."
  },
  {
    "id": "spirituality-002",
    "title": "Our existence was probably not intentionally created",
    "status": "endorsed",
    "confidence": "medium",
    "lastReviewed": "2026-08-02",
    "tags": [
      "origins",
      "simulation",
      "creation"
    ],
    "domain": "spirituality",
    "currentPoints": [
      "I do not think anything intentionally or explicitly created us.",
      "A simulation is a possible exception.",
      "I assign a relatively high chance to us being in a simulation, similar to Scott Alexander’s view on Astral Codex Ten."
    ],
    "notYetSettled": [
      "My exact probability of living in a simulation.",
      "Exactly which parts of Scott Alexander’s argument I agree with."
    ],
    "sourcePath": "beliefs/spirituality/our-existence-was-probably-not-intentionally-created.md",
    "githubUrl": "https://github.com/benson/worldview/blob/main/beliefs/spirituality/our-existence-was-probably-not-intentionally-created.md",
    "searchText": "our existence was probably not intentionally created spirituality origins simulation creation i do not think anything intentionally or explicitly created us. a simulation is a possible exception. i assign a relatively high chance to us being in a simulation, similar to scott alexander’s view on astral codex ten."
  },
  {
    "id": "spirituality-001",
    "title": "Suffering does not logically disprove God",
    "status": "endorsed",
    "confidence": "medium",
    "lastReviewed": "2026-08-02",
    "tags": [
      "theodicy",
      "suffering",
      "god",
      "argument-from-evil"
    ],
    "domain": "spirituality",
    "currentPoints": [
      "I think “there’s no God because how could he let there be suffering?” is a weak argument against God.",
      "“It’s better to have some happiness than no happiness” feels like a logical possible answer to that objection.",
      "This is not my explanation of reality. I do not think God intentionally created us.",
      "I do not think “trading” happiness between people is the right framing.",
      "I agree there should be an individual moral floor, but I have not defined it.",
      "I think people need the ability to feel both joy and sadness, but I have not worked out how that fits into the argument."
    ],
    "notYetSettled": [
      "How the ability to feel both joy and sadness fits into this argument.",
      "How to define the individual moral floor.",
      "How much suffering should count as evidence against different ideas of God, even if it is not a logical disproof."
    ],
    "sourcePath": "beliefs/spirituality/suffering-does-not-logically-disprove-god.md",
    "githubUrl": "https://github.com/benson/worldview/blob/main/beliefs/spirituality/suffering-does-not-logically-disprove-god.md",
    "searchText": "suffering does not logically disprove god spirituality theodicy suffering god argument-from-evil i think “there’s no god because how could he let there be suffering?” is a weak argument against god. “it’s better to have some happiness than no happiness” feels like a logical possible answer to that objection. this is not my explanation of reality. i do not think god intentionally created us. i do not think “trading” happiness between people is the right framing. i agree there should be an individual moral floor, but i have not defined it. i think people need the ability to feel both joy and sadness, but i have not worked out how that fits into the argument."
  },
  {
    "id": "politics-003",
    "title": "The response to the established unauthorized population is unresolved",
    "status": "tentative",
    "confidence": "low",
    "lastReviewed": "2026-08-02",
    "tags": [
      "immigration",
      "deportation",
      "legalization",
      "citizenship",
      "amnesty"
    ],
    "domain": "politics",
    "currentPoints": [
      "I have not decided whether adults already here illegally should be gradually deported or offered a one-time legalization program.",
      "Eventual slow and steady deportation of everyone who knowingly came or stayed illegally is not morally untenable to me.",
      "I am also open to a one-time reset because government and enforcement failures have allowed whole lives and industries to be built around the current system.",
      "One possible reset would let people come forward for lawful residence and work authorization, but not citizenship.",
      "I do not want people who came illegally to get ahead of people following the legal immigration process.",
      "Any reset would be a pragmatic response to systemic failure, not a moral entitlement earned by remaining illegally for long enough."
    ],
    "notYetSettled": [
      "How many people would be affected and what gradual enforcement would look like.",
      "Whether a reset should provide temporary status, permanent residence, citizenship, voting rights, or family-sponsorship rights.",
      "Whether permanent residence without citizenship is a fair consequence or an unacceptable permanent nonvoting class.",
      "Whether granting lifetime residence would itself unfairly skip the legal immigration line."
    ],
    "sourcePath": "beliefs/politics/response-to-the-established-unauthorized-population.md",
    "githubUrl": "https://github.com/benson/worldview/blob/main/beliefs/politics/response-to-the-established-unauthorized-population.md",
    "searchText": "the response to the established unauthorized population is unresolved politics immigration deportation legalization citizenship amnesty i have not decided whether adults already here illegally should be gradually deported or offered a one-time legalization program. eventual slow and steady deportation of everyone who knowingly came or stayed illegally is not morally untenable to me. i am also open to a one-time reset because government and enforcement failures have allowed whole lives and industries to be built around the current system. one possible reset would let people come forward for lawful residence and work authorization, but not citizenship. i do not want people who came illegally to get ahead of people following the legal immigration process. any reset would be a pragmatic response to systemic failure, not a moral entitlement earned by remaining illegally for long enough."
  }
];
